# dataloader configs
data_dir: "../../../../data/polar"
model_type: 'traditional'
semkitti_config: "semantic-kitti.yaml"
grid_size: [480,360,32]
max_vol: [50,50,1.5]
min_vol: [-50,-50,-3]
reflection: True

# augmentations
augmentations:
  fixed_vol: True
  flip: False
  rot: False

#training configs
model_save_path: "models/BEV_UNet.pt"
backbone: "UNet"
train_batch: 2
valid_batch: 2
num_workers: 4
lr_rate: 0.02
val_check_interval: 4000

# logging
logging: True
wandb_project: "polarseg-kitti"

