# dataloader configs
data_dir: "data/debug"
projection_type: 'polar'
semkitti_config: "semantic-kitti.yaml"
grid_size: [480,360,32] 
max_vol: [50,50,1.5]
min_vol: [-50,-50,-3]

# augmentations
augmentations:
  fixed_vol: True
  flip: True
  rot: True
  circular_padding: True

#training configs
model_save_path: "models/debug.pt"
backbone: "UNet"
train_batch: 2
valid_batch: 2
test_batch: 1
LARS: False
num_workers: 4
lr_rate: 0.02
val_check_interval: 500
max_epochs: 30
sampling: "random"

# logging
logging: True
wandb_project: "polarseg-kitti"

