# dataloader configs
data_dir: "data/debug"
model_type: 'traditional'
semkitti_config: "semantic-kitti.yaml"
grid_size: [480,360,32]
max_vol: [50,50,1.5]
min_vol: [-50,-50,-3]
reflection: True

# augmentations
augmentations:
  fixed_vol: False
  flip: False
  rot: False

#training configs
model_save_path: "models/debug.pt"
train_batch: 2
valid_batch: 2
num_workers: 4
lr_rate: 0.02
val_check_interval: 500

# logging
logging: True
wandb_project: "polarseg-kitti"

