# dataloader configs
data_dir: "/home/jumin/Dataset/dataset"
projection_type: 'cartesian'
semkitti_config: "references/semantic-kitti.yaml"
grid_size: [480,360,32] 
max_vol: [50,50,1.5]
min_vol: [-50,-50,-3]

# augmentations
augmentations:
  fixed_vol: True
  flip: True
  rot: True
  9features: True
  circular_padding: False

#training configs
model_save_path: "models/FCN_cart.pt"
backbone: "FCN"
train_batch: 2
valid_batch: 2
test_batch: 1
LARS: False
num_workers: 4
gpu : 0
lr_rate: 0.02
val_check_interval: 4000
max_epochs: 20
sampling: "random"

# logging
logging: False
wandb_project: "polarseg-kitti"
